# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ops/ml_api.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ops/ml_api.proto\x12\x06ml_api\"J\n\x11UploadDataRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x11\n\tfile_data\x18\x02 \x03(\x0c\x12\x13\n\x0b\x62\x61se64_data\x18\x03 \x03(\t\"\'\n\x12UploadDataResponse\x12\x11\n\tupload_id\x18\x01 \x01(\t\"!\n\x10GetStatusRequest\x12\r\n\x05token\x18\x01 \x01(\t\"#\n\x11GetStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"X\n\rActionRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\'\n\x0b\x61\x63tion_type\x18\x02 \x01(\x0e\x32\x12.ml_api.ActionType\x12\x0f\n\x07payload\x18\x03 \x01(\t\"2\n\x0e\x41\x63tionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t\"X\n\x0f\x44ownloadRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12#\n\tfile_type\x18\x02 \x01(\x0e\x32\x10.ml_api.FileType\x12\x11\n\tupload_id\x18\x03 \x01(\t\"&\n\x10\x44ownloadResponse\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c*$\n\nActionType\x12\x0b\n\x07PREDICT\x10\x00\x12\t\n\x05TRAIN\x10\x01*#\n\x08\x46ileType\x12\x07\n\x03LOG\x10\x00\x12\x0e\n\nCHECKPOINT\x10\x01\x32\x91\x02\n\tMLService\x12\x43\n\nUploadData\x12\x19.ml_api.UploadDataRequest\x1a\x1a.ml_api.UploadDataResponse\x12@\n\tGetStatus\x12\x18.ml_api.GetStatusRequest\x1a\x19.ml_api.GetStatusResponse\x12>\n\rExecuteAction\x12\x15.ml_api.ActionRequest\x1a\x16.ml_api.ActionResponse\x12=\n\x08\x44ownload\x12\x17.ml_api.DownloadRequest\x1a\x18.ml_api.DownloadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ops.ml_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ACTIONTYPE']._serialized_start=489
  _globals['_ACTIONTYPE']._serialized_end=525
  _globals['_FILETYPE']._serialized_start=527
  _globals['_FILETYPE']._serialized_end=562
  _globals['_UPLOADDATAREQUEST']._serialized_start=28
  _globals['_UPLOADDATAREQUEST']._serialized_end=102
  _globals['_UPLOADDATARESPONSE']._serialized_start=104
  _globals['_UPLOADDATARESPONSE']._serialized_end=143
  _globals['_GETSTATUSREQUEST']._serialized_start=145
  _globals['_GETSTATUSREQUEST']._serialized_end=178
  _globals['_GETSTATUSRESPONSE']._serialized_start=180
  _globals['_GETSTATUSRESPONSE']._serialized_end=215
  _globals['_ACTIONREQUEST']._serialized_start=217
  _globals['_ACTIONREQUEST']._serialized_end=305
  _globals['_ACTIONRESPONSE']._serialized_start=307
  _globals['_ACTIONRESPONSE']._serialized_end=357
  _globals['_DOWNLOADREQUEST']._serialized_start=359
  _globals['_DOWNLOADREQUEST']._serialized_end=447
  _globals['_DOWNLOADRESPONSE']._serialized_start=449
  _globals['_DOWNLOADRESPONSE']._serialized_end=487
  _globals['_MLSERVICE']._serialized_start=565
  _globals['_MLSERVICE']._serialized_end=838
# @@protoc_insertion_point(module_scope)
